name: CI CD Proccess Mitra Panca

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout

      uses: actions/checkout@v2

    - name: Deployment

      run: |

          cd /home/mitrapancabersama/htdocs/mitrapancabersama.com

          git checkout -f
          
          git pull
    - name: Install dependencies
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
      run: |
        set -e
        composer install || composer update
    - run : |
          cd /home/mitrapancabersama/htdocs/mitrapancabersama.com
          
    - run : systemctl restart nginx
